name: Push File

on:
  push:
  workflow_dispatch:
    inputs:
      update:
        description: "Update the zig source code"
        required: true
        type: boolean

permissions: write-all
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download source
        run: |
          curl -O "https://ziglang.org/builds/zig-0.14.0-dev.2851+b074fb7dd.tar.xz"
          
      - name: Commit and push changes
        run: |
          git config --local user.name "actions"
          git config --local user.email "actions@github.com"
          git add *
          git commit -m "2025-01-20 Update zig-0.14.0-dev.2851+b074fb7dd.tar.xz"
          git push origin master
