name: Push File

on:
  push:
  workflow_dispatch:
    inputs:
      update:
        description: "Update the zig source code"
        required: true
        type: boolean

permissions: write-all
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download source
        run: |
          curl -O "https://ziglang.org/builds/zig-linux-x86_64-0.14.0-dev.2847+db8ed730e.tar.xz"
          
      - name: Commit and push changes
        run: |
          git config --local user.name "actions"
          git config --local user.email "actions@github.com"
          git add .
          git commit -m "(buildable) 2025-01-19 Update https://ziglang.org/builds/zig-linux-x86_64-0.14.0-dev.2847+db8ed730e.tar.xz"
          git push origin master
